import type { Product, Sale, Customer, Supplier, Purchase } from '$lib/types';

// ─── Core helpers ─────────────────────────────────────────────────────────────

function csvCell(v: unknown): string {
	const s = v === null || v === undefined ? '' : String(v);
	if (s.includes(',') || s.includes('"') || s.includes('\n') || s.includes('\r')) {
		return '"' + s.replace(/"/g, '""') + '"';
	}
	return s;
}

export function formatCurrency(n: number | null | undefined): string {
	if (n === null || n === undefined) return '0.00';
	return new Intl.NumberFormat('en-KE', {
		minimumFractionDigits: 2,
		maximumFractionDigits: 2
	}).format(n);
}

export function formatDate(d: string | null | undefined): string {
	if (!d) return '';
	return new Date(d).toLocaleDateString('en-GB', {
		day: '2-digit', month: 'short', year: 'numeric'
	});
}

export function formatPercent(n: number): string {
	return n.toFixed(1) + '%';
}

function buildCSV(headers: string[], rows: string[][]): string {
	const lines = [headers.map(csvCell).join(','), ...rows.map(r => r.map(csvCell).join(','))];
	return lines.join('\r\n');
}

const BOM = '\uFEFF'; // UTF-8 BOM for Excel

export function downloadCSV(content: string, filename: string): void {
	const blob = new Blob([BOM + content], { type: 'text/csv;charset=utf-8;' });
	const url = URL.createObjectURL(blob);
	const a = document.createElement('a');
	a.href = url;
	a.download = filename;
	document.body.appendChild(a);
	a.click();
	document.body.removeChild(a);
	URL.revokeObjectURL(url);
}

export function safeFilename(shopName: string, module: string, ext = 'csv'): string {
	const date = new Date().toISOString().slice(0, 10);
	const safe = (shopName || 'Export').replace(/[^a-zA-Z0-9]/g, '_').replace(/_+/g, '_');
	return `${safe}_${module}_${date}.${ext}`;
}

// ─── Meta header ─────────────────────────────────────────────────────────────

function metaHeader(shopName: string, exportedBy: string, module: string): string {
	const lines = [
		`# Shop: ${shopName}`,
		`# Module: ${module}`,
		`# Export Date: ${new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'long', year: 'numeric' })}`,
		`# Generated By: ${exportedBy}`,
		``
	];
	return lines.join('\r\n');
}

// ─── Per-module exporters ─────────────────────────────────────────────────────

export function exportProducts(products: Product[], shopName: string, exportedBy: string): string {
	const headers = [
		'Product Name', 'Barcode', 'SKU', 'Category',
		'Buying Price (KES)', 'Selling Price (KES)', 'Profit Margin (%)',
		'Current Stock', 'Reorder Level', 'Status', 'Created Date'
	];
	const rows = products.map(p => {
		const margin = p.buying_price > 0
			? ((p.selling_price - p.buying_price) / p.buying_price * 100)
			: 0;
		return [
			p.name,
			p.barcode ?? '',
			p.sku ?? '',
			p.category_name ?? '',
			formatCurrency(p.buying_price),
			formatCurrency(p.selling_price),
			formatPercent(margin),
			String(p.stock_qty),
			String(p.reorder_level),
			p.is_active ? 'Active' : 'Inactive',
			formatDate(p.created_at)
		];
	});
	return metaHeader(shopName, exportedBy, 'Products') + buildCSV(headers, rows);
}

export function exportSales(sales: Sale[], shopName: string, exportedBy: string): string {
	const headers = [
		'Receipt No', 'Customer', 'Cashier', 'Payment Method',
		'Date', 'Time', 'Subtotal (KES)', 'Discount (KES)',
		'Tax (KES)', 'Grand Total (KES)', 'Status'
	];
	const rows = sales.map(s => [
		s.id.slice(0, 10).toUpperCase(),
		s.customer_name ?? 'Walk-in',
		s.cashier_name ?? '',
		s.payment_method.toUpperCase(),
		formatDate(s.created_at),
		new Date(s.created_at).toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit' }),
		formatCurrency(s.subtotal),
		formatCurrency(s.discount),
		formatCurrency(s.tax),
		formatCurrency(s.total),
		s.status
	]);
	return metaHeader(shopName, exportedBy, 'Sales') + buildCSV(headers, rows);
}

export function exportCustomers(customers: Customer[], shopName: string, exportedBy: string): string {
	const headers = [
		'Customer Name', 'Phone', 'Email', 'Address', 'Date Created'
	];
	const rows = customers.map(c => [
		c.name,
		c.phone ?? '',
		c.email ?? '',
		c.address ?? '',
		formatDate(c.created_at)
	]);
	return metaHeader(shopName, exportedBy, 'Customers') + buildCSV(headers, rows);
}

export function exportSuppliers(suppliers: Supplier[], shopName: string, exportedBy: string): string {
	const headers = [
		'Supplier Name', 'Phone', 'Email', 'Address', 'Date Created'
	];
	const rows = suppliers.map(s => [
		s.name,
		s.phone ?? '',
		s.email ?? '',
		s.address ?? '',
		formatDate(s.created_at)
	]);
	return metaHeader(shopName, exportedBy, 'Suppliers') + buildCSV(headers, rows);
}

export function exportPurchases(purchases: Purchase[], shopName: string, exportedBy: string): string {
	const headers = [
		'Purchase No', 'Supplier', 'Ordered By', 'Date',
		'Items Count', 'Total Cost (KES)', 'Status', 'Notes'
	];
	const rows = purchases.map(p => [
		p.id.slice(0, 10).toUpperCase(),
		p.supplier_name ?? '',
		p.user_name ?? '',
		formatDate(p.created_at),
		String(p.items?.length ?? 0),
		formatCurrency(p.total),
		p.status,
		p.note ?? ''
	]);
	return metaHeader(shopName, exportedBy, 'Purchases') + buildCSV(headers, rows);
}

export interface InventoryRow {
	product_name: string;
	stock_qty: number;
	reorder_level: number;
	buying_price: number;
	selling_price: number;
	category_name?: string | null;
}

export function exportInventory(rows: InventoryRow[], shopName: string, exportedBy: string): string {
	const headers = [
		'Product', 'Category', 'Current Stock', 'Reorder Level',
		'Stock Status', 'Inventory Value (KES)', 'Retail Value (KES)'
	];
	const csvRows = rows.map(r => {
		const status = r.stock_qty <= 0 ? 'Out of Stock'
			: r.stock_qty <= r.reorder_level ? 'Low Stock'
			: 'In Stock';
		return [
			r.product_name,
			r.category_name ?? '',
			String(r.stock_qty),
			String(r.reorder_level),
			status,
			formatCurrency(r.buying_price * r.stock_qty),
			formatCurrency(r.selling_price * r.stock_qty)
		];
	});
	return metaHeader(shopName, exportedBy, 'Inventory') + buildCSV(headers, csvRows);
}
